### ISSUE TITLE
opam installation

### ISSUE THREAD

**Issue by selig** [c-cube/zipperposition#2]
I tried to install zipperposition using opam and got the following error

    =-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
    [ERROR] The compilation of qbf failed at "./configure --enable-quantor
            --disable-depqbf --docdir=/Users/giles/.opam/system/doc
            --disable-random".
    ∗  installed gen.0.2.4
    ∗  installed msat.1.1
    ∗  installed ppx_deriving.3.0
    ∗  installed sequence.0.5.5
    ∗  installed containers.0.13
    ∗  installed logtk.0.8
    
    #=== ERROR while installing qbf.0.1 ===========================================#
    # opam-version 1.2.1
    # os           darwin
    # command      ./configure --enable-quantor --disable-depqbf --docdir=/Users/giles/.opam/system/doc --disable-random
    # path         /Users/giles/.opam/system/build/qbf.0.1
    # compiler     system (4.02.2)
    # exit-code    1
    # env-file     /Users/giles/.opam/system/build/qbf.0.1/qbf-38252-8c0dd3.env
    # stdout-file  /Users/giles/.opam/system/build/qbf.0.1/qbf-38252-8c0dd3.out
    # stderr-file  /Users/giles/.opam/system/build/qbf.0.1/qbf-38252-8c0dd3.err
    ### stdout ###
    # -n cc ...
    # [...]
    # -n cflags ...
    #   -W -Wall -fPIC -static -DNDEBUG -O3
    # -n makefile ...
    #  done
    # rm -f config.h; ./mkconfig > config.h
    # gcc -W -Wall -fPIC -static -DNDEBUG -O3 -c picosat.c
    # gcc -W -Wall -fPIC -static -DNDEBUG -O3 -c app.c
    # gcc -W -Wall -fPIC -static -DNDEBUG -O3 -c main.c
    # gcc -W -Wall -fPIC -static -DNDEBUG -O3 -o picosat main.o app.o picosat.o
    ### stderr ###
    # picosat.c:3748:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    # [...]
    # picosat.c:3754:7: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    #        while (++i < rcount && *CLS2ACT (resolved[i]) < min_cls_activity)
    #        ^
    # ld: library not found for -lcrt0.o
    # collect2: error: ld returned 1 exit status
    # make[2]: *** [picosat] Error 1
    # make[1]: *** [all] Error 2
    # make: *** [deps] Error 2
    # E: Failure("Command 'make deps' terminated with error code 2")

**Comment by c-cube** [comment]
Strange. The failure is in [OCaml-qbf](https://github.com/c-cube/ocaml-qbf), not in Zipperposition, but still. What OS are you using?

**Comment by selig** [comment]
I'm on a Mac (OS X Yosemite 10.10.4) so my OCaml and opam are from macports.

**Comment by c-cube** [comment]
And can you compile a normal C program using gcc? I don't have a mac so, sadly, I cannot try to reproduce the bug...

**Comment by selig** [comment]
Yes but static compilation is an issue, is there a reason the library needs to be statically compiled?

Don't worry too much; I will fall back to my Linux box if this isn't easy to resolve.

**Comment by c-cube** [comment]
I'm not sure, I don't maintain the QBF solver. I think static linking of `crt` might be necessary, as I suspect it is the C runtime library. Sorry for that.

**Comment by c-cube** [comment]
This issue has become irrelevant w.r.t the incoming 1.0 release that doesn't rely on qbf.
