### ISSUE TITLE
How to access Logtk

### ISSUE THREAD

**Issue by darrenldl** [c-cube/zipperposition#36]
Sorry if this is not a proper issue, but I am very confused with regards to using logtk as a library.

Since logtk now ships with zipperposition, should it be the case that logtk is still accessible? Cause I can't seem to be able to use it even after installing zipperposition via opam.

Cheers,
Darren

**Comment by c-cube** [comment]
No worries. On opam there's a version (1.5) that doesn't install the dependencies but just builds them as it builds zipperposition. That's not the case on master, so I recommend trying `opam pin https://github.com/c-cube/zipperposition.git#master` which should pin `logtk`, `libzipperposition`, and `zipperposition`. If you want you can also git clone the repository and `opam pin` your local version.

**Comment by darrenldl** [comment]
The pinning works fine, thanks!

Also, I will be working on a research project that most likely require me to implement unification with associativity, commutativity, associativity & commutativity, and XOR. And it is quite likely I will implement these using the Logtk library.

Would these unification algorithms be of interest to you guys? If so I will file a PR toward the end of the project.

**Comment by c-cube** [comment]
It could be of interest if you can contribute them, sure.

For a bit of context, the terms in logtk are polymorphic higher-order terms, with hashconsing (at least for `Term.t`). You may want to simply fail on lambda-abstractions and bound variables if you don't use them, the first-order (typed) fragment is plenty useful already.

By curiosity, is your work related to cryptographic protocols in any way?

**Comment by darrenldl** [comment]
> By curiosity, is your work related to cryptographic protocols in any way?

Yes, it is related to automatic verification of such protocols. The XOR unification gave it away didn't it.

I'm gonna close the issue here, but we can talk on gitter or email if you're interested in extending the conversation.

Thanks again for the quick reply!
