### ISSUE TITLE
Type syntax in "zf" files

### ISSUE THREAD

**Issue by delahayd** [c-cube/zipperposition#4]
Hello,

Would it be possible to get a more compact notation for explicit types when several variables have the same type? For example:

val foo : pi (a b : type)...

rather than

val foo : pi (a : type) (b : type)...

I could use type inference but I rely on another tool (not zipperposition), which uses "zf" files but does not support type inference.

Thanks a lot,

David.

**Comment by c-cube** [comment]
It should work now. I added a small test in `tests/poly.zf` using the new syntax. Note that it only works for `pi` right now, if you want the same for, say, forall, please reopen the issue.

**Comment by delahayd** [comment]
Thanks a lot! Yes, for "forall" as well, it would be perfect ;-)...

**Comment by c-cube** [comment]
`forall (x y : nat) …` works now. You still need several `( ... )` blocks for variables with different types.
